# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('site', models.CharField(max_length=1000)),
                ('score', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='combine.Url'),
        ),
    ]
