# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('data', models.BinaryField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
