# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0002_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
