import re
import os


sub = (("appy polly loggy", "apology"),
       ("baboochka", "old woman"),
       ("baddiwad", "bad"),
       ("banda", "band"),
       ("bezoomny", "mad"),
       ("biblio", "library"),
       ("bitva", "battle"),
       ("Bog", "God"),
       ("bolnoy", "sick"),
       ("bolshy", "big,"),
       ("brat", "brother"),
       ("bratty", "brother"),
       ("bratchny", "bastard"),
       ("britva", "razor"),
       ("brooko", "belly"),
       ("brosay", "to throw"),
       ("bugatty", "rich"),
       ("al", "feces"),
       ("cancer", "cigarette"),
       ("cantora", "office"),
       ("carman", "pocket"),
       ("chai", "tea"),
       ("choodesny", "wonderful"),
       ("chumble", "to mumble"),
       ("clop", "to knock"),
       ("cluve", "beak"),
       ("collocoll", "bell"),
       ("crack", "to break up or 'bust'"),
       ("crark", "to yowl?"),
       ("crast", "to steal or rob"),
       ("creech", "to shout or scream"),
       ("cutter", "money"),
       ("dama", "lady"),
       ("ded", "old man"),
       ("deng", "money"),
       ("devotchka", "girl"),
       ("dobby", "good"),
       ("dook", "trace, ghost"),
       ("domy", "house"),
       ("dorogoy", "dear, valuable"),
       ("dratsing", "fighting"),
       ("drencrom", "drug"),
       ("charles", "chaplain"),
       ("charlie", "chaplain"),
       ("droog", "friend"),
       ("chasha", "cup"),
       ("dung", "to defecate"),
       ("chasso", "guard"),
       ("dva", "two"),
       ("cheena", "woman"),
       ("eegra", "game"),
       ("cheest", "to wash"),
       ("eemya", "name"),
       ("chelloveck", "person, man"),
       ("eggiweg", "egg"),
       ("filly", "to play or fool with"),
       ("chepooka", "nonsense"),
       ("firegold", "drink"),
       ("fist", "to punch"),
       ("flip", "wild?"),
       ("forella", "'trout'"),
       ("gazetta", "newspaper"),
       ("glazz", "eye"),
       ("gloopy", "stupid"),
       ("golly", "unit of money"),
       ("goloss", "voice"),
       ("goober", "lip"),
       ("gooly", "to walk"),
       ("gorlo", "throat"),
       ("govoreet", "to speak or talk"),
       ("grahzny", "dirty"),
       ("loveted", "caught"),
       ("lubbilubbing", "making love"),
       ("luscious glory", "hair"),
       ("malchick", "boy"),
       ("malenky", "little, tiny"),
       ("maslo", "butter"),
       ("merzky", "filthy"),
       ("messel", "thought, fancy"),
       ("mesto", "place"),
       ("millicent", "policeman"),
       ("minoota", "minute"),
       ("molodoy", "young"),
       ("moloko", "milk"),
       ("grazzy", "soiled"),
       ("gromky", "loud"),
       ("groody", "breast"),
       ("gruppa", "group"),
       ("guff", "guffaw"),
       ("gulliver", "head"),
       ("guttiwuts", "guts"),
       ("hen-korm", "chickenfeed"),
       ("horn", "to cry out"),
       ("horrorshow", "good, well"),
       ("in-out in-out", "copulation"),
       ("interessovat", "to interest"),
       ("itty", "to go"),
       ("jammiwam", "jam"),
       ("jeezny", "life"),
       ("kartoffel", "potato"),
       ("keeshkas", "guts"),
       ("kleb", "bread"),
       ("klootch", "key"),
       ("knopka", "button"),
       ("kopat", "to 'dig'"),
       ("koshka", "cat"),
       ("kot", "tomcat"),
       ("krovvy", "blood"),
       ("kupet", "to buy"),
       ("lapa", "paw"),
       ("lewdies", "people"),
       ("lighter", "crone?"),
       ("litso", "face"),
       ("lomtick", "piece, bit"),
       ("platties", "clothes"),
       ("pletcho", "shoulder"),
       ("plenny", "prisoner"),
       ("plesk", "splash"),
       ("plosh", "to splash"),
       ("plott", "body"),
       ("podooshka", "pillow"),
       ("pol", "sex"),
       ("polezny", "useful"),
       ("polyclef", "skeleton key"),
       ("pony", "to understand"),
       ("poogly", "frightened"),
       ("pooshka", "'cannon'"),
       ("prestoopnick", "criminal"),
       ("privodeet", "to lead somewhere"),
       ("pretty polly", "money"),
       ("prod", "to produce"),
       ("ptitsa", "'chick'"),
       ("moodge", "man"),
       ("morder", "snout"),
       ("mounch", "snack"),
       ("mozg", "brain"),
       ("nachinat", "to begin"),
       ("nadmenny", "arrogant"),
       ("nadsat", "teenage"),
       ("nagoy", "naked"),
       ("nazz", "fool"),
       ("neezhnies", "underpants"),
       ("nochy", "night"),
       ("hoga", "foot, leg"),
       ("nozh", "knife"),
       ("nuking", "smelling oddy"),
       ("knocky", "lonesome"),
       ("odin", "one"),
       ("okno", "window"),
       ("oobivat", "to kill"),
       ("ookadeet", "to leave"),
       ("ooko", "ear"),
       ("oomny", "brainy"),
       ("oozhassny", "terrible"),
       ("oozy", "chain"),
       ("osoosh", "to wipe"),
       ("otchkies", "eyeglasses"),
       ("pan-handle", "erection"),
       ("pee and em", "parents"),
       ("peet", "to drink"),
       ("pishcha", "food"),
       ("platch", "to cry"),
       ("shlaga", "club"),
       ("shlapa", "hat"),
       ("shoom", "noise"),
       ("shoot", "fool"),
       ("sinny", "cinema"),
       ("skazat", "to say"),
       ("skolliwoll", "school"),
       ("skorry", "quick, quickly"),
       ("skriking", "scratching"),
       ("skvat", "to grab"),
       ("sladky", "sweet"),
       ("sloochat", "to happen"),
       ("sloosh, slooshy", "to hear, to listen"),
       ("slovo", "word"),
       ("smeck", "laugh"),
       ("smot", "to look"),
       ("sneety", "dream"),
       ("snoutie", "tobacco?"),
       ("pyahnitsa", "drunk"),
       ("rabbit", "work, job"),
       ("radosty", "joy"),
       ("raskazz", "story"),
       ("rassoodock", "mind"),
       ("raz", "time"),
       ("razdraz", "upset"),
       ("razrez", "to rip, ripping"),
       ("rook, rooker", "hand, arm"),
       ("rot", "mouth"),
       ("rozz", "policeman"),
       ("sabog", "shoe"),
       ("sakar", "sugar"),
       ("sammy", "generous"),
       ("sarky", "sarcastic"),
       ("scoteena", "'cow'"),
       ("shaika", "gang"),
       ("sharp", "female"),
       ("sharries", "buttocks"),
       ("shest", "barrier"),
       ("shilarny", "concern"),
       ("shive", "slice"),
       ("shiyah", "neck"),
       ("shlem", "helmet"),
       ("viddy", "to see or look"),
       ("voloss", "hair"),
       ("von", "smell"),
       ("vred", "to harm or damage"),
       ("yahma", "hole"),
       ("yahoodies", "Jews"),
       ("yahzick", "tongue"),
       ("yarbles", "testicles"),
       ("snuff it", "to die"),
       ("sobirat", "to pick up"),
       ("sod", "to fornicate, fornicator"),
       ("soomka", "'bag'"),
       ("soviet", "advice, order"),
       ("spat", "to sleep"),
       ("splodge, splosh", "splash"),
       ("spoogy", "terrified"),
       ("Staja", "State Jail"),
       ("starry", "ancient"),
       ("strack", "horror"),
       ("synthemesc", "drug"),
       ("tally", "waist"),
       ("tashtook", "handkerchief"),
       ("tass", "cup"),
       ("tolchock", "to hit or push; blow, beating"),
       ("toofles", "slippers"),
       ("tree", "three"),
       ("vareet", "to 'cook up'"),
       ("vaysay", "washroom"),
       ("veck", "(see chelloveck)"),
       ("vellocet", "drug"),
       ("veshch", "thing"),
       ("yeckate", "to drive"),
       ("warble", "song"),
       ("zammechat", "remarkable"),
       ("zasnoot", "sleep"),
       ("zheena", "wife"),
       ("zoobies", "teeth"),
       ("zvonock", "bellpull"),
       ("zvook", "sound"))


def fix(s):
    for x in sub:
        word, dfn = x
        s = re.compile("\\b({}{})([a-z-]*)".format(
            word, "\\b" if len(word) < 4 else ""), re.I).sub(
                "\\1\\2 [[{}]]\\2".format(dfn), s)
    return s


for f in os.listdir("0"):
    if f.endswith(".xhtml"):
        p = os.path.join("0", f)
        with open(p, "r") as fp:
            s = fp.read()
        s = fix(s)
        with open(p, "w") as fp:
            fp.write(s)
