#!/bin/bash
#
# This script can be used to add git-annex metadata to files when they're
# committed. It is typically installed as .git/hooks/pre-commit-annex
#
# You can also run this script by hand, passing it the names of files
# already checked into git-annex, and it will extract/refresh the git-annex
# metadata from the files.

set -e
set -x

process() {
    if [ -e "$1" ]; then
        git -c annex.alwayscommit=false annex metadata \
            --set "mtime?=$(stat --printf=%y "$1")" -- "$1"
    fi
}

if [ "$#" -gt 0 ]; then
	for f in "$@"; do
		process "$f"
	done
else
        if git rev-parse --verify HEAD >/dev/null 2>&1; then
                against="HEAD"
        else
                # Initial commit: diff against an empty tree object
                against="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
        fi
	git diff-index --name-only --cached $against | while read f; do
		process "$f"
	done
fi
